version: "3.8"
services:
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "6001:80"
    nodeserveruno:
        build:
            context: ./serveruno
        ports:
            - "6000:6000"